# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values fo not exceed four million, find the sum of the even-valued terms

def even_fibonacci_numbers(n):
    if n < 2:
        return 0
    else:
        prev = 0
        curr = 2
        sum = 0
        while curr < n:
            sum += curr
            temp = prev
            prev = curr
            curr = prev*4 + temp

        return sum

print(even_fibonacci_numbers(4000000))